### ISSUE TITLE
How to install 

### ISSUE THREAD

**Issue by Manishfoodtechs** [mohssineAboutaj/web-to-apk#1]
Can you help people without knowledge of Android and Java how to install this?

**Comment by mohssineAboutaj** [comment]
Hi @Manishfoodtechs tnanks for your asking
to be honest it's not my project, and i'm not an Andoird dev but i can help you as i can
- first of all you need to install [Andoird Studio](https://developer.android.com/studio?gclid=Cj0KCQjwyYKUBhDJARIsAMj9lkG5yHVk8wLAfpbVwd-7Oyt4dJg2HPMD0_eQWyMbm1P2sQYOvhFAAtoaApfzEALw_wcB&gclsrc=aw.ds) in your machine, 
- open the project on it
- then edit the value exists in `./app/src/main/java/com/example/najmus/webtoapp/MainActivity.java` called `mywebView.loadUrl` and put your custom URL

**Comment by Manishfoodtechs** [comment]
Thanks for this

**Comment by mohssineAboutaj** [comment]
your are welcome
i will close this issue, but you can asking anytime
